### PR TITLE
UPDATE[CREATE INITIAL BACKEND PROJECT DIRECTORY]

### PR DESCRIPTION
**Pull request by sparkyPythoneer**

### CODE REVIEW

**Comment by sparkyPythoneer** [comment]
@chukaibejih 

Kindly confirm that this is fine, I boxed the Django project though.

**Comment by sparkyPythoneer** [comment]
@chukaibejih
If you're cool with this, help merge it into the development branch

Hence, we can pull development to begin our implementations as indicated in the Channel.

**Comment by chukaibejih** [comment]
> @chukaibejih
> 
> Kindly confirm that this is fine, I boxed the Django project though.

Okay. I am taking a look at it now.

**Review by chukaibejih — APPROVED** [review]
This is good enough for us to start with.

**Pull request merged**
